//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Info
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School_Entities : DbContext
    {
        public School_Entities()
            : base("name=School_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Class { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<Subjects> Subjects { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<fees> fees { get; set; }
        public DbSet<Periods> Periods { get; set; }
        public DbSet<Attendance> Attendance { get; set; }
    }
}
