//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.fees = new HashSet<fees>();
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string RollNo { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<fees> fees { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
    }
}
