//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int Id { get; set; }
        public string SubjectsName { get; set; }
    
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
